Updated workflow to stop running with no changes

diff --git a/.github/workflows/screenshot.yml b/.github/workflows/screenshot.yml
--- a/.github/workflows/screenshot.yml
+++ b/.github/workflows/screenshot.yml
@@ -28,13 +28,15 @@ jobs:
         run: |
           sed -i 's/\!\[Webpage Screenshot\].*/\!\[Webpage Screenshot\](screenshot.png)/' README.md
 
+      - name: Check for Changes
+        run: |
+          git diff --quiet || git commit -am "Update screenshot [skip ci]"
+
       - name: Commit and Push Updated Screenshot
         run: |
           git config --global user.name 'Your CI/CD'
           git config --global user.email 'ci-cd@example.com'
-          git add screenshot.png README.md
-          git commit -m "Update screenshot [skip ci]"
 
-          # Use the GitHub token as a secret
+          # Set up the Git remote with the token
           git remote add origin_with_token https://$GH_TOKEN@github.com/cassia102/Alpaca-Image-Generator.git
-          git push origin_with_token main
+          git push origin_with_token main || echo "Failed to push changes"
